from app.database import SessionLocal
from app.services.semantic_retrieval import (
    SemanticRetrievalService,
)


def main():
    db = SessionLocal()

    try:
        service = SemanticRetrievalService()

        candidates = service.retrieve_candidates(
            db=db,
            column_name="revenue",
            column_description=(
                "Revenue generated by the business account."
            ),
            dataset_domain="Customer / Account Management",
            table_context="Business account records",
            top_k=5,
        )

        print("\nTop semantic candidates:\n")

        for index, candidate in enumerate(
            candidates,
            start=1,
        ):
            print(
                f"{index}. "
                f"{candidate['concept']} "
                f"({candidate['similarity']:.4f})"
            )

    finally:
        db.close()


if __name__ == "__main__":
    main()