from app.database import SessionLocal
from app.services.semantic_analysis import (
    SemanticAnalysisService,
)


def main():
    db = SessionLocal()

    try:
        service = SemanticAnalysisService()

        result = service.analyze_column(
            db=db,
            column_name="revenue",
            column_description=(
                "Revenue generated by the business account."
            ),
            data_type="float64",
            profile={
                "column_name": "revenue",
                "data_type": "float64",
                "row_count": 85,
                "null_count": 0,
                "null_percentage": 0.0,
                "empty_string_count": 0,
                "empty_string_percentage": 0.0,
                "whitespace_only_count": 0,
                "whitespace_only_percentage": 0.0,
                "distinct_count": 85,
                "distinct_percentage": 100.0,
                "duplicate_count": 0,
                "duplicate_excess_count": 0,
                "identifier_name_signal": False,
                "identifier_completeness_percentage": 100.0,
                "identifier_uniqueness_percentage": 100.0,
                "identifier_signal": False,
                "numeric": {
                    "count": 85,
                    "min": 4.54,
                    "max": 11698.03,
                    "mean": 1994.6329411764705,
                    "median": 1223.72,
                    "std": 2169.491436349182,
                    "q25": 497.11,
                    "q50": 1223.72,
                    "q75": 2741.37,
                    "iqr": 2244.2599999999998,
                    "mad": 896.9000000000001,
                    "outlier_count_iqr": 6,
                    "outlier_percentage_iqr": 7.0588235294117645,
                    "near_constant": False,
                },
            },
            dataset_domain="Customer / Account Management",
            table_context=(
                "Business account records with "
                "financial information."
            ),
            top_k=5,
        )
        print("\nSemantic Analysis Result\n")
        print(
            "Column:",
            result["column"],
        )
        print(
            "Concept:",
            result["semantic_concept"],
        )
        print(
            "Concept ID:",
            result["concept_id"],
        )
        print(
            "Confidence:",
            result["confidence_score"],
        )
        print(
            "Level:",
            result["confidence_level"],
        )

        print("\nEvidence:")

        for key, value in result[
            "evidence"
        ].items():
            print(
                f"  {key}: {value}"
            )

        print("\nAlternatives:")

        for alternative in result[
            "alternatives"
        ]:
            print(
                f"  {alternative['concept']}: "
                f"{alternative['score']}"
            )

    finally:
        db.close()


if __name__ == "__main__":
    main()