import json

from sqlalchemy.orm import Session

from app.models import SemanticConcept


CONCEPTS = [
    {
        "concept_id": "C001",
        "concept_name": "Customer ID",
        "category": "Identifier",
        "description": "Unique identifier assigned to a customer.",
        "aliases": ["customer_id", "customer number", "cust_id", "cust_no"],
        "expected_data_types": ["int", "string"],
        "profile_expectations": {
            "identifier_like": True,
            "unique": True,
            "non_null": True,
        },
    },
    {
        "concept_id": "C002",
        "concept_name": "Account ID",
        "category": "Identifier",
        "description": "Unique identifier assigned to a business or customer account.",
        "aliases": ["account_id", "account number", "account code", "account_no"],
        "expected_data_types": ["int", "string"],
        "profile_expectations": {
            "identifier_like": True,
            "unique": True,
            "non_null": True,
        },
    },
    {
        "concept_id": "C003",
        "concept_name": "Product ID",
        "category": "Identifier",
        "description": "Unique identifier assigned to a product.",
        "aliases": ["product_id", "product code", "product number", "sku"],
        "expected_data_types": ["int", "string"],
        "profile_expectations": {
            "identifier_like": True,
            "unique": True,
            "non_null": True,
        },
    },
    {
        "concept_id": "C004",
        "concept_name": "Order ID",
        "category": "Identifier",
        "description": "Unique identifier assigned to a customer order or transaction.",
        "aliases": ["order_id", "order number", "order code", "order_no"],
        "expected_data_types": ["int", "string"],
        "profile_expectations": {
            "identifier_like": True,
            "unique": True,
            "non_null": True,
        },
    },
    {
        "concept_id": "C005",
        "concept_name": "Revenue",
        "category": "Financial Measure",
        "description": "Revenue generated by a business, account, customer, or transaction.",
        "aliases": ["revenue", "sales", "turnover", "sales revenue"],
        "expected_data_types": ["int", "float"],
        "profile_expectations": {
            "numeric": True,
            "non_negative": True,
            "continuous": True,
        },
    },
    {
        "concept_id": "C006",
        "concept_name": "Price",
        "category": "Financial Measure",
        "description": "Monetary price associated with a product, item, or service.",
        "aliases": ["price", "unit price", "selling price", "item price"],
        "expected_data_types": ["int", "float"],
        "profile_expectations": {
            "numeric": True,
            "non_negative": True,
        },
    },
    {
        "concept_id": "C007",
        "concept_name": "Quantity",
        "category": "Measure",
        "description": "Number of units, items, or products associated with a transaction.",
        "aliases": ["quantity", "qty", "units", "item count"],
        "expected_data_types": ["int", "float"],
        "profile_expectations": {
            "numeric": True,
            "non_negative": True,
        },
    },
    {
        "concept_id": "C008",
        "concept_name": "Employee Count",
        "category": "Business Measure",
        "description": "Number of employees working for an organization or business.",
        "aliases": ["employees", "employee count", "number of employees", "staff count"],
        "expected_data_types": ["int", "float"],
        "profile_expectations": {
            "numeric": True,
            "non_negative": True,
        },
    },
    {
        "concept_id": "C009",
        "concept_name": "Email",
        "category": "Contact Information",
        "description": "Electronic mail address used to contact a person or organization.",
        "aliases": ["email", "email address", "mail address"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "text": True,
            "email_pattern": True,
        },
    },
    {
        "concept_id": "C010",
        "concept_name": "Phone Number",
        "category": "Contact Information",
        "description": "Telephone number used to contact a person or organization.",
        "aliases": ["phone", "phone number", "mobile", "telephone"],
        "expected_data_types": ["string", "int"],
        "profile_expectations": {
            "text": True,
            "phone_pattern": True,
        },
    },
    {
        "concept_id": "C011",
        "concept_name": "Date",
        "category": "Temporal",
        "description": "Calendar date representing when an event, transaction, or record occurred.",
        "aliases": ["date", "calendar date", "record date"],
        "expected_data_types": ["date", "datetime", "string"],
        "profile_expectations": {
            "temporal": True,
        },
    },
    {
        "concept_id": "C012",
        "concept_name": "Age",
        "category": "Demographic",
        "description": "Age of a person, customer, passenger, or employee.",
        "aliases": ["age", "person age", "customer age"],
        "expected_data_types": ["int", "float"],
        "profile_expectations": {
            "numeric": True,
            "non_negative": True,
            "bounded": True,
        },
    },
    {
        "concept_id": "C013",
        "concept_name": "Gender",
        "category": "Demographic",
        "description": "Gender or sex classification associated with a person.",
        "aliases": ["gender", "sex"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "categorical": True,
        },
    },
    {
        "concept_id": "C014",
        "concept_name": "Country",
        "category": "Geographic",
        "description": "Country associated with a person, organization, address, or transaction.",
        "aliases": ["country", "country name", "nation"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "categorical": True,
        },
    },
    {
        "concept_id": "C015",
        "concept_name": "City",
        "category": "Geographic",
        "description": "City or locality associated with a person, organization, or address.",
        "aliases": ["city", "city name", "town", "locality"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "categorical": True,
        },
    },
    {
        "concept_id": "C016",
        "concept_name": "Postal Code",
        "category": "Geographic",
        "description": "Postal or ZIP code associated with a geographic address.",
        "aliases": ["postal code", "zip code", "zipcode", "pin code"],
        "expected_data_types": ["string", "int"],
        "profile_expectations": {
            "categorical": True,
            "postal_pattern": True,
        },
    },
    {
        "concept_id": "C017",
        "concept_name": "Status",
        "category": "Business Attribute",
        "description": "Current state or status of a business entity, record, transaction, or process.",
        "aliases": ["status", "state", "current status", "record status"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "categorical": True,
        },
    },
    {
        "concept_id": "C018",
        "concept_name": "Address",
        "category": "Geographic",
        "description": "Physical or mailing address associated with a person, organization, or location.",
        "aliases": ["address", "street address", "mailing address", "office address"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "text": True,
        },
    },
    {
        "concept_id": "C019",
        "concept_name": "Company Name",
        "category": "Business Attribute",
        "description": "Name of a company, organization, or business entity.",
        "aliases": ["company", "company name", "organization", "business name"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "text": True,
        },
    },
        {
        "concept_id": "C031",
        "concept_name": "Parent Company",
        "category": "Business Relationship",
        "description": "Name or identifier of the parent company or organization that owns or controls another company or subsidiary.",
        "aliases": [
            "parent company",
            "parent organization",
            "holding company",
            "subsidiary parent",
            "owned by",
        ],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "text": True,
        },
    },
    {
        "concept_id": "C020",
        "concept_name": "Industry Sector",
        "category": "Business Attribute",
        "description": "Industry or business sector in which an organization operates.",
        "aliases": ["sector", "industry", "industry sector", "business sector"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "categorical": True,
        },
    },
    {
        "concept_id": "C021",
        "concept_name": "Year Established",
        "category": "Business Attribute",
        "description": "Year in which a company or organization was established.",
        "aliases": ["year established", "founded year", "established year", "foundation year"],
        "expected_data_types": ["int"],
        "profile_expectations": {
            "numeric": True,
            "year": True,
        },
    },
    {
        "concept_id": "C022",
        "concept_name": "Transaction Date",
        "category": "Temporal",
        "description": "Date or timestamp when a financial or business transaction occurred.",
        "aliases": ["transaction date", "txn date", "purchase date", "order date"],
        "expected_data_types": ["date", "datetime", "string"],
        "profile_expectations": {
            "temporal": True,
        },
    },
    {
        "concept_id": "C023",
        "concept_name": "Customer Name",
        "category": "Person / Customer",
        "description": "Name of a customer or individual associated with a customer record.",
        "aliases": ["customer name", "customer", "client name", "client"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "text": True,
        },
    },
    {
        "concept_id": "C024",
        "concept_name": "Product Name",
        "category": "Product Attribute",
        "description": "Name or descriptive label assigned to a product.",
        "aliases": ["product name", "product", "item name", "item"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "text": True,
        },
    },
    {
        "concept_id": "C025",
        "concept_name": "Description",
        "category": "Text Attribute",
        "description": "Free-text description providing additional information about an entity or record.",
        "aliases": ["description", "details", "notes", "comments"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "text": True,
        },
    },
    {
        "concept_id": "C026",
        "concept_name": "Category",
        "category": "Classification",
        "description": "Classification or grouping assigned to an entity, product, or record.",
        "aliases": ["category", "class", "classification", "group"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "categorical": True,
        },
    },
    {
        "concept_id": "C027",
        "concept_name": "Discount",
        "category": "Financial Measure",
        "description": "Reduction applied to the original price or transaction amount.",
        "aliases": ["discount", "discount amount", "discount rate", "markdown"],
        "expected_data_types": ["int", "float"],
        "profile_expectations": {
            "numeric": True,
            "non_negative": True,
        },
    },
    {
        "concept_id": "C028",
        "concept_name": "Tax",
        "category": "Financial Measure",
        "description": "Tax amount or tax rate associated with a transaction or financial record.",
        "aliases": ["tax", "tax amount", "tax rate", "sales tax"],
        "expected_data_types": ["int", "float"],
        "profile_expectations": {
            "numeric": True,
            "non_negative": True,
        },
    },
    {
        "concept_id": "C029",
        "concept_name": "Currency",
        "category": "Financial Attribute",
        "description": "Currency in which a monetary value or transaction is expressed.",
        "aliases": ["currency", "currency code", "money type"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "categorical": True,
            "currency_code": True,
        },
    },
    {
        "concept_id": "C030",
        "concept_name": "Review Text",
        "category": "Text Attribute",
        "description": "Free-text review or feedback provided by a customer about a product or service.",
        "aliases": ["review", "review text", "feedback", "customer review", "comment"],
        "expected_data_types": ["string"],
        "profile_expectations": {
            "text": True,
            "long_text": True,
        },
    },
    {
    "concept_id": "C032",
    "concept_name": "Office Location",
    "category": "Geographic Information",
    "description": "Geographic location of the office, headquarters, or primary business location of an organization.",
    "aliases": [
        "office location",
        "office headquarters",
        "headquarters location",
        "business location",
        "company location",
        "hq location",
    ],
    "expected_data_types": ["string"],
    "profile_expectations": {
        "text": True,
        "categorical": True,
        },
    },
]


def seed_semantic_concepts(db: Session) -> int:
    """
    Insert the initial Semantic Knowledge Base.

    Existing concepts are not duplicated.
    """

    inserted = 0

    for item in CONCEPTS:
        existing = (
            db.query(SemanticConcept)
            .filter(
                SemanticConcept.concept_name
                == item["concept_name"]
            )
            .first()
        )

        if existing:
            continue

        concept = SemanticConcept(
            concept_name=item["concept_name"],
            category=item["category"],
            description=item["description"],
            aliases=json.dumps(item["aliases"]),
            expected_data_types=json.dumps(
                item["expected_data_types"]
            ),
            profile_expectations=json.dumps(
                item["profile_expectations"]
            ),
        )

        db.add(concept)
        inserted += 1

    db.commit()

    return inserted
